# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'LC_ALL=C echo ''sha: `git rev-parse HEAD | grep -oP '[[:alnum:]]+''`'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $env:ChocolateyInstall'
    pwsh: true
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      'New-Item $env:ChocolateyInstall\templates -ItemType Directory -Force'
      'Write-Host "blablabla" > $env:ChocolateyInstall\templates\mytemplate'
    pwsh: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Com.Github.Zycrophat.Serilog.Extensions/*.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Com.Github.Zycrophat.Serilog.Extensions'
    publishLocation: 'Container'

